name: IridiumEvents
author: skyphi
version: 1.0
api-version: 1.21
main: dev.skyphi.IridiumEvents
softdepend: ["PlaceholderAPI"]
commands:
  statistic:
    description: Gets a specific statistic for a given player
    usage: /<command> <player> <source> <statistic>
    default: op
    aliases: [stat]
  points:
    description: Gives or gets points
    usage: /<command> <give/get> <player> [#]